### ISSUE TITLE
书名号内只有一个字，整个句子会分为一个词

### ISSUE THREAD

**Issue by huntercmd** [thunlp/THULAC-Python#10]
书名号内只有一个字，整个句子会分为一个词，在线demo版也会有部分这样的问题，是训练模型的语料差别引起的吗？

#### python自带模型
句子：“没有一部能跟以前的佳作相提并论，意义何在？《我》纪录片形式根本不适合他”
结果：**没有一部能跟以前的佳作相提并论，意义何在？《我》纪录片形式根本不适合他_r**

句子：“没有一部能跟以前的佳作相提并论，意义何在？《我们》纪录片形式根本不适合他“
结果：没有_v 一_m 部_q 能_v 跟_p 以前_f 的_u 佳作_n 相提并论_id ，_w 意义_n 何在_v ？_w 《_w 我们_r 》_w 纪录片_n 形式_n 根本_d 不_d 适合_v 他_r

#### 在线demo
句子：“挺喜欢听人讲《洞》的跳跃式剪辑，为什么要这么干“
结果：“挺_d 喜欢_v 听_v 人_n 讲_v 《_w **洞》的跳跃式剪辑，为什么要这么干_c**”

句子：“挺喜欢听人讲《黑洞》的跳跃式剪辑，为什么要这么干“
结果：“挺_d 喜欢_v 听_v 人_n 讲_v 《_w 黑洞_n 》_w 的_u 跳跃_v 式_k 剪辑_v ，_w 为什么_r 要_v 这么_r 干_v”

**Comment by gzp9595** [comment]
非常感谢您对THULAC的支持，由于书名长度为1的时候为比较特殊的情况，我们已经修复~
