### ISSUE TITLE
断句信息

### ISSUE THREAD

**Issue by jamestch** [thunlp/THULAC-Python#17]
Hi,
使用cut_f对输入的文本进行分词、词性标注，获取的结果可以提供句子之间的间隔信息吗（断句）？还是我需要自己实现对句子进行断句，在调用cut函数对句子进行分词？

**Comment by MaJunhua** [comment]
感谢您的支持，THULAC目前没有内置断句功能。cut_f函数的原理是逐行对输入文件进行分词，同时将分词结果写到输出文件对应的每一行上。

**Comment by jamestch** [comment]
非常感谢您的回复，要是增加断句功能就更方便啦
