### ISSUE TITLE
train_c不知道使用

### ISSUE THREAD

**Issue by yangjiaronga** [thunlp/THULAC-Python#24]
我想使用训练模式, 但是教程只说
./train_c [-s separator] [-b bigram_threshold] [-i iteration] training_filename model_filename   
    使用training_filename为训练集，训练出来的模型名字为model_filename
train_c 我不知道在哪里找到

**Comment by gzp9595** [comment]
非常感谢对THULAC的支持，现在训练模型的程序只支持C++版本~
