### ISSUE TITLE
请问有分词后生成词汇表的功能吗

### ISSUE THREAD

**Issue by zhangpengGenedock** [thunlp/THULAC-Python#43]
如题

**Comment by gzp9595** [comment]
暂时没有的~

发送自 Windows 10 版邮件应用

发件人: zhangpeng
发送时间: 2017年9月18日 23:48
收件人: thunlp/THULAC-Python
抄送: Subscribed
主题: [thunlp/THULAC-Python] 请问有分词后生成词汇表的功能吗 (#43)

如题
