### ISSUE TITLE
用户词典部分词语没有生效

### ISSUE THREAD

**Issue by ashengtx** [thunlp/THULAC-Python#66]
在用户词典中含有这几个词，`皮皮虾`，`皮皮虾我们走`，`<song>`，`</song>`，分别对下面两个句子进行分词：
```
sent1 = '请拨皮皮虾我们走'
sent2 = '请拨<song>皮皮虾我们走</song>'
```
结果分别为
```
result1: ['请', '拨皮', '皮虾', '我们走']
result2: ['请', '拨', '<song>', '皮皮虾我们走', '</song>']
```
为什么会这样？用户词典中没有`拨皮`，也没有`皮虾`，`拨皮`也不是一个正常的词。
有没办法解决？

**Comment by gzp9595** [comment]
是这样的，我们的词表主要是使用后处理来进行，也就是如果分词时一个词被切分成了几部分，并且不是单独出现时，就不会强制进行合并处理
