### ISSUE TITLE
FILT的具体用法？

### ISSUE THREAD

**Issue by yyywhy** [thunlp/THULAC-Python#67]
filt                默认False, 是否使用过滤器去除一些没有意义的词语，例如“可以”。你们给的文档中是这么说的，那么的话我是否可以自行添加过滤内容？或者说你们有什么加强关键字提取准确性的方案吗？

**Comment by gzp9595** [comment]
过滤主要是在分词整体结束之后进行的后处理，我们使用了比较常用的stopwords的词表，这个在model中也能找到，如果需要可以自行修改~
