### ISSUE TITLE
user_dict

### ISSUE THREAD

**Issue by CGdeepvoice** [thunlp/THULAC-Python#72]
您好，最近在使用THULAC时，引用自己的字典，但是匹配时候还是有限使用了默认的
比如  ['小', 'a'], ['叶增生', 'np']  我在字典中加了 小叶 属于名词
请问是否可以优先使用自己的字典或者设置词频 提高user_dict的优先级？

**Comment by gzp9595** [comment]
暂时没有办法，因为如果将用户词典优先级提升，可能会造成无法分词
