### ISSUE TITLE
THULAC.so make时报错

### ISSUE THREAD

**Issue by HikaruSama233** [thunlp/THULAC-Python#76]
错误信息为：

g++ -O3 -I src src/thulac_lib.cc -shared -fPIC -Wl,-soname=libthulac.so.1 -o ./libthulac.so
/usr/bin/ld: skipping incompatible /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../libm.a when searching for -lm
/usr/bin/ld: skipping incompatible /lib/libm.a when searching for -lm
/usr/bin/ld: skipping incompatible /usr/lib/libm.a when searching for -lm
/usr/bin/ld: cannot find -lm
collect2: error: ld returned 1 exit status
make: *** [libthulac.so] Error 1

请问 lm 是什么？应该如何解决这个问题

**Comment by gzp9595** [comment]
是不是因为少了一些什么标准的库造成的？ 因为在 g++4.8.4 上测试没有发现问题
