### ISSUE TITLE
python 离线版问题

### ISSUE THREAD

**Issue by liutianfang** [thunlp/THULAC-Python#77]
记住玩具熊在沙发后面
[['记住', 'v'], ['玩具', 'n'], ['熊', 'v'], ['在', 'p'], ['沙发', 'n'], ['后面', 'f']]

在线demo版

记住_v 玩具_n 熊_n 在_p 沙发_n 后面_s

熊被标记为V

**Comment by gzp9595** [comment]
python版本直接下载的模型为model_1_2，
线上demo版本的模型为进一步优化的模型model_3
