### ISSUE TITLE
请问用户自定义词典可以标注多个词性吗？

### ISSUE THREAD

**Issue by ghost** [thunlp/THULAC-Python#81]
在自定义词典时，遇到一些二义性的问题，
1. 一个词可能既是动词也是名词，改如何处理呢？
2.自带词典中的词时名词，而希望将其在特定场合识别为数词，如何做呢？

**Comment by gzp9595** [comment]
1、一个词是动词还是名词主要由语境来决定，所以会根据上下文进行判定
2、通过现在的自定义字典还暂不支持，可以考虑修改代码上添加词典的地方满足条件。
