### ISSUE TITLE
character\CBTaggingDecoder.py:IndexError: list assignment index out of range

### ISSUE THREAD

**Issue by tianlef** [thunlp/THULAC-Python#87]
错误出现在CBTaggingDecoder.py 第165行：
        self.allowedLabelLists[i] = self.pocsToTags[pocs]
可能是self.allowedLabelLists列表为空时，进行[0]赋值。

File "thu_txt.py", line 50, in <module>
    segment = thu1.cut(puretext, text=True)  #进行一句话分词

  File "D:\Anaconda3\lib\site-packages\thulac\__init__.py", line 107, in cut
    return self.__cutWithOutMethod(oiraw, self.__cutline, text = text)

  File "D:\Anaconda3\lib\site-packages\thulac\__init__.py", line 89, in __cutWithOutMethod
    temp_txt = reduce(lambda x, y: x + ' ' + y if y != " " else x, cut_method(line), '') + '\n'

  File "D:\Anaconda3\lib\site-packages\thulac\__init__.py", line 131, in __cutline
    tmp, tagged = self.__cws_tagging_decoder.segmentTag(raw, __poc_cands)

  File "D:\Anaconda3\lib\site-packages\thulac\character\CBTaggingDecoder.py", line 165, in segmentTag
    self.allowedLabelLists[i] = self.pocsToTags[pocs]

IndexError: list assignment index out of range

**Comment by GeekerSu** [comment]
> 错误出现在CBTaggingDecoder.py 第165行：
> self.allowedLabelLists[i] = self.pocsToTags[pocs]
> 可能是self.allowedLabelLists列表为空时，进行[0]赋值。
> 
> File "thu_txt.py", line 50, in
> segment = thu1.cut(puretext, text=True) #进行一句话分词
> 
> File "D:\Anaconda3\lib\site-packages\thulac__init__.py", line 107, in cut
> return self.__cutWithOutMethod(oiraw, self.__cutline, text = text)
> 
> File "D:\Anaconda3\lib\site-packages\thulac__init__.py", line 89, in __cutWithOutMethod
> temp_txt = reduce(lambda x, y: x + ' ' + y if y != " " else x, cut_method(line), '') + '\n'
> 
> File "D:\Anaconda3\lib\site-packages\thulac__init__.py", line 131, in __cutline
> tmp, tagged = self.__cws_tagging_decoder.segmentTag(raw, __poc_cands)
> 
> File "D:\Anaconda3\lib\site-packages\thulac\character\CBTaggingDecoder.py", line 165, in segmentTag
> self.allowedLabelLists[i] = self.pocsToTags[pocs]
> 
> IndexError: list assignment index out of range

我在用工具处理wiki的中文语料时也出现了这个报错，请问您是如何解决的呀

**Comment by duguiming111** [comment]
一句很普通的中文句子，分词也是这样，请问你是怎么解决的呢？
